---
title: "The fars package"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Overview of the fars package}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r, echo = FALSE, include = FALSE}
library(fars)
library(dplyr)
library(maps)
```

This vignette provides a brief overview of the FARS package.

## Functions

The functions available to users are described below:

- `fars_summarize_years()`
- `fars_map_state()`

### fars_read

The function `fars_read()` provides a way how to read data from a file path provided as an argument. It returns a `tibble` with loaded data:

**Examples**

 `fars_read("accident_2013.csv.bz2")`

## Summarize number of accidents

The next function `fars_summarize_years()` takes a vector or list of years (numeric/integer values) as an argument and if the corresponding files with data are available, it returns a pivot table with number of accidents per year and month. The data files need to be located in the working directory.

**Examples**

 `fars_summarize_years("2015")`
 
## Plot accident locations

The last function available in the package, `fars_map_state()` takes a state index and year as arguments and returns a plot of the state with accident locations. The state indices need to correspond available indeces from the data set. Here are some examples:

**Examples**

  `fars_map_state(1,2013)`
  
Note that the data file needs to be present in the working directory. 
